version: '3'
services:
  web:
    build:
      context: ./modxServer
    links:
      - 'db:mysql'
    ports:
      - '443:443'
      - '80:80'
    environment:
      XDEBUG_SESSION: wtf
      MODX_VERSION: 2.8.1
      MODX_CORE_LOCATION: /var/www/coreM0dXF1L3s
      MODX_DB_HOST: 'mysql:3306'
      MODX_DB_PASSWORD: modx
      MODX_DB_USER: modx
      MODX_DB_NAME: modx
      MODX_TABLE_PREFIX: modx_
      MODX_ADMIN_USER: admin
      MODX_ADMIN_PASSWORD: admin
      MODX_ADMIN_EMAIL: admin@admin.com
      MODX_SERVER_ROUTE: 192.168.0.104
    volumes:
      - '~/development/PROJECT_FOLDER_LOCATION/www:/var/www'
  db:
    image: 'mysql:8.0.22'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: modx
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - '~/development/PROJECT_FOLDER_LOCATION/mysql:/var/lib/mysql'
