version: '3'
services:
  web:
    build:
      context: ./modxServer
    links:
      - 'db:mysql'
    depends_on:
      - db
    ports:
      - '443:443'
      - '80:80'
      - '8080:8080'
      - '9090:9090'
      - '5173:5173'
    environment:
      XDEBUG_SESSION: wtf
      MODX_VERSION: 2.8.1
      MODX_CORE_LOCATION: /var/www/html/core
      MODX_DB_HOST: 'mysql:3306'
      MODX_DB_PASSWORD: modx
      MODX_DB_USER: modx
      MODX_DB_NAME: modx
      MODX_TABLE_PREFIX: modx_
      MODX_ADMIN_USER: admin
      MODX_ADMIN_PASSWORD: admin
      MODX_ADMIN_EMAIL: admin@admin.com
      MODX_SERVER_ROUTE: 192.168.0.107
      WSLIP: 172.17.0.1
      TZ: America/Bogota
    volumes:
      - './www:/var/www'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
  db:
    image: 'mysql:8.0.22'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: modx
      MYSQL_USER: modx
      MYSQL_PASSWORD: modx
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './mysql:/var/lib/mysql'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M


